### ISSUE TITLE
Apologies if we're spamming, but proper credit really needs to be given.

### ISSUE THREAD

**Issue by Denverplays2** [LynxCGames/Alternate_Paths#7]
Unlike the other people of the BTDX server, I actually really like this mod, and find it neat that several of the BTDX ideas were ported over here. However, proper credit still really needs to be given to Ramaf and BTDX for several of the 4th Path upgrades. Much love, and I hope you can correct this soon.

Have a nice day, 
Paul.

**Comment by AGuyThatDoesTh1ngs** [comment]
We really are not trying to be mean, all we are asking for is proper credit
